name: SignStatus
main: SignStatus\SignStatus
version: 4.0.0
author: SuperKali
api:
- 2.0.0
- 1.12.1
- 1.13.0
load: POSTWORLD
permissions:
 signstatus:
  default: op
  description: Can create status sign
